export const organizationGovernorates = [
    "Cairo",
    "Alexandria",
    "Giza",
    "Luxor",
    "Aswan",
    "Suez",
    "Ismailia",
    "Port Said",
    "Red Sea",
    "Damietta",
    "Beheira",
    "Qalyubia",
    "Minya",
    "Sohag",
    "Qena",
    "Assiut",
    "Beni Suef",
    "Faiyum",
    "Matrouh",
    "Kafr El Sheikh",
    "Asyut",
    "Sharqia",
    "Gharbia",
    "North Sinai",
    "South Sinai",
    "New Valley",
    "Menofia",
    "Dakahlia",
    "Marsa Matruh"
];
